-- 2026-03-19: 为 WMS_SHELF_DETAIL 表添加 BIN_SIZE 字段
-- 用于标识货架的库位大小（普通货架=1，大盘货架=3）

-- 添加 BIN_SIZE 字段，默认值为 1
ALTER TABLE WMS_SHELF_DETAIL ADD BIN_SIZE INT NOT NULL DEFAULT 1;

-- 更新大盘货架的 BIN_SIZE 为 3
-- 当前大盘货架: SHELF_NO = 'L110A' (3库位一个大盘)
UPDATE WMS_SHELF_DETAIL SET BIN_SIZE = 3 WHERE SHELF_NO = 'L110A';

-- 验证
-- SELECT SHELF_NO, BIN_NO, BIN_SIZE FROM WMS_SHELF_DETAIL WHERE SHELF_NO = 'L110A';
