-- Pick locking concurrency hardening
-- Target table: CUS_PICKING_LOCK_BARNO

BEGIN TRANSACTION;

-- 1) 清理历史重复 BAR_NO（保留最新一条）
;WITH Dedup AS (
    SELECT
        GUID,
        BAR_NO,
        ROW_NUMBER() OVER (
            PARTITION BY BAR_NO
            ORDER BY CREATE_TIME DESC, GUID DESC
        ) AS RN
    FROM CUS_PICKING_LOCK_BARNO
    WHERE BAR_NO IS NOT NULL
)
DELETE FROM CUS_PICKING_LOCK_BARNO
WHERE GUID IN (
    SELECT GUID
    FROM Dedup
    WHERE RN > 1
);

-- 2) BAR_NO 全局唯一（过滤空值）
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_CUS_PICKING_LOCK_BARNO_BAR_NO'
      AND object_id = OBJECT_ID('CUS_PICKING_LOCK_BARNO')
)
BEGIN
    CREATE UNIQUE INDEX UX_CUS_PICKING_LOCK_BARNO_BAR_NO
    ON CUS_PICKING_LOCK_BARNO(BAR_NO)
    WHERE BAR_NO IS NOT NULL;
END

-- 3) DOC_NO + BAR_NO 查询索引
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_CUS_PICKING_LOCK_BARNO_DOCNO_BARNO'
      AND object_id = OBJECT_ID('CUS_PICKING_LOCK_BARNO')
)
BEGIN
    CREATE INDEX IX_CUS_PICKING_LOCK_BARNO_DOCNO_BARNO
    ON CUS_PICKING_LOCK_BARNO(DOC_NO, BAR_NO);
END

COMMIT TRANSACTION;
