-- 2026-03-20: 为 CUS_PICKING_LOCK_BARNO 表添加 WAREHOUSE_LOCATION 字段
-- 用于区分不同仓库的锁定记录
-- BUG2 修复：Picking 锁定条码缺少仓库信息

-- 添加 WAREHOUSE_LOCATION 字段
ALTER TABLE CUS_PICKING_LOCK_BARNO ADD WAREHOUSE_LOCATION NVARCHAR(50) NULL;

-- 验证
-- SELECT DOC_NO, BAR_NO, WAREHOUSE_LOCATION FROM CUS_PICKING_LOCK_BARNO;
